language: c
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - docker-ce
      - pep8
services:
  - docker
env:
  - OS_TYPE=centos:7
  - OS_TYPE=opensuse/leap:15
  - OS_TYPE=ubuntu:18.04
  - OS_TYPE=debian:9
  - OS_TYPE=centos:7 BUILD_MODE=sanitize
before_install:
  - .github/runchecks
  - docker pull ${OS_TYPE}
  - '[ "${OS_TYPE}" == "ubuntu:18.04" -o "${OS_TYPE}" == "debian:9" ] && export DOCKER_EXTRA_ARG="-e DEBIAN_FRONTEND=noninteractive" || true'
  - docker run -it -d -h testdev.pbspro.org --name testdev -v $(pwd):$(pwd) --privileged -w $(pwd) ${DOCKER_EXTRA_ARG} ${OS_TYPE} /bin/bash
  - docker ps -a
  - export DOCKER_EXEC="docker exec -it ${DOCKER_EXTRA_ARG} --privileged testdev"
install:
  - '[ "x${BUILD_MODE}" == "xsanitize" ] && ${DOCKER_EXEC} .travis/do_sanitize_mode.sh || true'
  - '[ "x${BUILD_MODE}" != "xsanitize" ] && ${DOCKER_EXEC} .travis/do.sh || true'
  - docker exec -it -w $(pwd)/test/tests testdev /bin/bash -lc 'pbs_benchpress --tags=smoke'
script: true
